[env:es3c28p]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.psram_type = opi
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -I../../include
    -I../../common
    -Isrc
    -DUSER_SETUP_LOADED=1
    -DILI9341_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MISO=13
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_DC=46
    -DTFT_RST=-1
    -DTFT_BL=45
    -DTFT_BACKLIGHT_ON=HIGH
    -DSPI_FREQUENCY=40000000
lib_deps =
    bodmer/TFT_eSPI@^2.5.43

build_src_filter = +<*> +<../../common/>
